[package]
name = "pv"
version = "0.0.1"
edition = "2021"
authors = ["Mike Kot <to@myrrc.dev>"]

[profile.release]
opt-level = "z"
lto = "thin"
panic = "abort"
strip = true

[dependencies]
termion = "1.5.6"
mini_markdown = "0.2.8"
