name: Publish

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
    - name: Install compressor
      run: sudo apt install -y upx

    - uses: actions/checkout@v3
    
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --release
    - name: Test
      run: cargo test --release
    
    - name: Compress
      run: upx --best target/release/pv
      
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: pv
        path: target/release/pv
